package info.futureme.abs.example.entity.g;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "attachment".
 */
public class Attachment {

    private Long id;
    private String type;
    private String ticketid;
    private Integer status;
    private String clientName;
    private String path;
    private String lazyId;
    private Integer failedTime;
    private String account;
    private Long time;

    public Attachment() {
    }

    public Attachment(Long id) {
        this.id = id;
    }

    public Attachment(Long id, String type, String ticketid, Integer status, String clientName, String path, String lazyId, Integer failedTime, String account, Long time) {
        this.id = id;
        this.type = type;
        this.ticketid = ticketid;
        this.status = status;
        this.clientName = clientName;
        this.path = path;
        this.lazyId = lazyId;
        this.failedTime = failedTime;
        this.account = account;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTicketid() {
        return ticketid;
    }

    public void setTicketid(String ticketid) {
        this.ticketid = ticketid;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getClientName() {
        return clientName;
    }

    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getLazyId() {
        return lazyId;
    }

    public void setLazyId(String lazyId) {
        this.lazyId = lazyId;
    }

    public Integer getFailedTime() {
        return failedTime;
    }

    public void setFailedTime(Integer failedTime) {
        this.failedTime = failedTime;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

}
