package info.futureme.abs.example.entity.g;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "filecache".
 */
public class FileCache {

    private Long id;
    private String url;
    private String path;
    private String source_type;
    private String content_type;
    private Long timestamp;

    public FileCache() {
    }

    public FileCache(Long id) {
        this.id = id;
    }

    public FileCache(Long id, String url, String path, String source_type, String content_type, Long timestamp) {
        this.id = id;
        this.url = url;
        this.path = path;
        this.source_type = source_type;
        this.content_type = content_type;
        this.timestamp = timestamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getSource_type() {
        return source_type;
    }

    public void setSource_type(String source_type) {
        this.source_type = source_type;
    }

    public String getContent_type() {
        return content_type;
    }

    public void setContent_type(String content_type) {
        this.content_type = content_type;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

}
