package info.futureme.abs.example.entity.g;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "station".
 */
public class Station {

    private Long id;
    private Integer level;
    private String stationCode;
    private String stationPrefix;

    public Station() {
    }

    public Station(Long id) {
        this.id = id;
    }

    public Station(Long id, Integer level, String stationCode, String stationPrefix) {
        this.id = id;
        this.level = level;
        this.stationCode = stationCode;
        this.stationPrefix = stationPrefix;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public String getStationCode() {
        return stationCode;
    }

    public void setStationCode(String stationCode) {
        this.stationCode = stationCode;
    }

    public String getStationPrefix() {
        return stationPrefix;
    }

    public void setStationPrefix(String stationPrefix) {
        this.stationPrefix = stationPrefix;
    }

}
