package info.futureme.abs.example.entity.g;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "locationdetail".
 */
public class UploadLocation {

    private Long id;
    private String location;
    private Double latitude;
    private Double longtitude;

    public UploadLocation() {
    }

    public UploadLocation(Long id) {
        this.id = id;
    }

    public UploadLocation(Long id, String location, Double latitude, Double longtitude) {
        this.id = id;
        this.location = location;
        this.latitude = latitude;
        this.longtitude = longtitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongtitude() {
        return longtitude;
    }

    public void setLongtitude(Double longtitude) {
        this.longtitude = longtitude;
    }

}
